### ISSUE TITLE
How cpu read the data ?

### ISSUE THREAD

**Issue by gliangMT** [DippyArtu/complex_opencl#1]
Hi !
I want to know how to pass data between host and devices? It seems like that host `cl_complex` can not be read by cpu .Could you please show an examples?

**Comment by DippyArtu** [comment]
hi! 
cl_complex is not meant to be included into the host program, please treat this library as any other library, only you include it inside your kernel

for the host, you can either define your own class, or, better yet, use the complex.h library

when developing this, i haven’t had the need to return complex numbers from the kernel, but there are a few ways you can achieve this:

you could, for example, define 2 arrays — 1st will store real part, 2nd will store imaginary

or you could do the same with 2d arrays (i.e. number[i][n]) 

or, you can try to define a structure and pass the structure into the kernel and back

remember, that complex numbers are basically just 2 numbers, feel free to get creative!

i have also written a boilerplate-tutorial-something for using OpenCL, which includes examples of working with multidimensional arrays and structures, feel free to have a look!

https://github.com/DippyArtu/libcl

**Comment by gliangMT** [comment]
Thanks a lot! That will be very useful to me!

**Comment by DippyArtu** [comment]
you are very welcome!
